services:
  frontend:
    build:
      context: frontend
    env_file:
      - ./.env
    volumes:
      - frontend:/app/frontend/dist

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    networks:
      - internal

  backend:
    build:
      context: backend
    env_file:
      - ./.env
    volumes:
      - ./backend/src:/app/src
      - public:/app/src/public
    ports:
      - 3000:3000
    networks:
      - internal
    depends_on:
      - mongo
    restart: unless-stopped

  server:
    build:
      context: nginx
    ports:
      - 80:80
    volumes:
      - frontend:/var/app
      - public:/var/public
    depends_on:
      - frontend
      - backend
    networks:
      - internal
    restart: unless-stopped

volumes:
  frontend:
  public:
  db:

networks:
  internal:
